name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間のお昼12時
    - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update Artwork data
        run: deno task update
        env:
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
