name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間 火曜日の深夜0時（水曜日）
    - cron: "0 15 * * 2"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update Artwork data
        run: deno task update
        env:
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
