name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間 毎月1日
    - cron: "* 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Fetch New Artwork Data
        id: update
        run: |
          deno task update
          data=$(cat ./data.json)
          data="${data//$'\n'/\\n}"
          echo "::set-output name=data::$data"
        env:
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

      - name: Send to Slack
        if: hashFiles('data.json') != ''
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C03JQ4MPLMN'
          payload: |
            {
              "text": "DBを更新しました",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "DBを更新しました\n```\n${{ steps.update.outputs.data }}\n```"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload to DB
        if: hashFiles('data.json') != ''
        run: deno task upload
        env:
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
